/*
 * Acts as the TCP server bridging Unity and an external ML client (Python).
 * 
 * Key responsibilities:
 *   - Listen for a single client connection.
 *   - Transmit basic metadata (observation/action vector lengths) once on connect, and again after each environment reset.
 *   - Support opcode-based communication protocol:
 *          0  =>  Step      (expects an action float array)
 *          1  =>  Reset     (expects a random seed int)
 *   - Perform thread‑safe exchange of data between the network thread and Unity’s main thread.
 * 
 * Revision notes:
 *   - Introduced dynamic handshake including obs/action sizes.
 *   - Retained multi‑thread design for Unity API isolation.
 *   - Added detailed lifecycle logging for clarity.

 * This script was initially generated by OpenAI's GPT5 model, then studied and re-commented by me.
 *
 */

using System;
using System.Net;
using System.Net.Sockets;
using System.Threading;
using System.IO;
using UnityEngine;

public class EnvironmentSocketServer : MonoBehaviour
{
    [Header("Unity Environment Link")]
    [Tooltip("Script managing simulation stepping and resetting.")]
    public EnvironmentController envController;

    [Header("Network Settings")]
    [Tooltip("TCP port to listen on for Python clients.")]
    public int port = 5005;

    // ===== Internal server state =====
    private TcpListener listener;
    private Thread listenThread;
    private volatile bool running = false;

    // ===== Thread‑synchronisation objects =====
    private AutoResetEvent actionAvailable = new AutoResetEvent(false);
    private AutoResetEvent responseReady = new AutoResetEvent(false);

    // ===== Data exchange buffers =====
    private float[] pendingAction = null;             // action array waiting for execution
    private byte[] pendingResponse = null;            // serialized observation+reward+done to return
    private volatile bool resetRequested = false;     // flag: network requested environment reset
    private int pendingSeed = 0;                      // seed accompanying pending reset

    // =============================================================================================

    void Start()
    {
        if (envController == null)
        {
            Debug.LogError("EnvironmentController reference missing.");
            enabled = false;
            return;
        }

        // Spawn dedicated network listener thread
        listenThread = new Thread(ListenForClient);
        listenThread.IsBackground = true;
        listenThread.Start();

        running = true;
        Debug.Log($"[SocketServer] Listening on port {port}");
    }

    void OnApplicationQuit()
    {
        running = false;
        try { listener?.Stop(); } catch { }
        actionAvailable.Set();
        responseReady.Set();
        listenThread?.Join(500);       // Attempt graceful shutdown within 0.5s
    }

    // =============================================================================================
    // NETWORK THREAD — handles all socket I/O
    // =============================================================================================

    private void ListenForClient()
    {
        try
        {
            listener = new TcpListener(IPAddress.Any, port);
            listener.Start();


            while (running)
            {
                /*// Allow Unity to quietly drop second evaluation connection until training finishes
                if (listener.Pending() && running)
                {
                    Debug.LogWarning("[SocketServer] Ignoring new client connection; already connected.");
                    Thread.Sleep(1000);
                    continue;
                }*/
                using (TcpClient client = listener.AcceptTcpClient())
                using (NetworkStream ns = client.GetStream())
                using (BinaryReader br = new BinaryReader(ns))
                using (BinaryWriter bw = new BinaryWriter(ns))
                {
                    ns.ReadTimeout = 60000; // 60s initial timeout - python client takes time to start
                    ns.WriteTimeout = 2000;
                    Debug.Log("[SocketServer] Client connected.");

                    // Initial handshake
                    SendHandshake(bw);

                    while (running && client.Connected)
                    {
                        int opCode;
                        try
                        {
                            opCode = br.ReadInt32();
                            ns.ReadTimeout = 2000; // after first read, reduce timeout to 2s
                        }
                        catch (IOException ex)
                        {
                            Debug.LogWarning("[SocketServer] Lost client or invalid opcode read:\n" + ex.Message);
                            break;
                        }

                        if (opCode == 1) // ---- RESET ----
                        {
                            int seed = br.ReadInt32();
                            pendingSeed = seed;
                            resetRequested = true;
                            actionAvailable.Set();           // wake Unity thread

                            responseReady.WaitOne();         // wait for Unity main thread
                            bw.Write(0);                     // keep legacy empty ack for backward compat
                            bw.Flush();
                            continue;
                        }
                        else if (opCode == 0) // ---- STEP ----
                        {
                            int actionLen = br.ReadInt32();
                            float[] action = new float[actionLen];
                            for (int i = 0; i < actionLen; i++) { action[i] = br.ReadSingle(); }

                            pendingAction = action;
                            actionAvailable.Set();

                            // Wait for result
                            responseReady.WaitOne();

                            int respLen = pendingResponse?.Length ?? 0;
                            bw.Write(respLen);
                            if (respLen > 0) { bw.Write(pendingResponse, 0, respLen); }
                            bw.Flush();

                            pendingAction = null;
                            pendingResponse = null;
                        }
                        else
                        {
                            Debug.LogWarning($"[SocketServer] Unknown opcode ({opCode}). Disconnecting.");
                            break;
                        }

                        Debug.Log($"running: {running}, connected: {client.Connected}");
                    }

                    Debug.Log("[SocketServer] Client disconnected.");
                }
            }
        }
        catch (SocketException ex)
        {
            // Common benign case: play‑mode exit interrupts socket unexpectedly
            if (!running && ex.SocketErrorCode == SocketError.Interrupted) return;
            Debug.LogError($"[SocketServer] Socket error: {ex}");
        }
    }

    // =============================================================================================
    // MAIN UNITY THREAD — processes actions and resets
    // =============================================================================================

    void Update()
    {
        // ---- Handle a reset request ----
        if (resetRequested)
        {
            UnityEngine.Random.InitState(pendingSeed);
            envController.ResetEnvironment();

            resetRequested = false;
            responseReady.Set(); // Allow network thread to proceed
        }

        // ---- Handle a simulation step ----
        if (pendingAction != null)
        {
            var (obs, reward, done) = envController.Step(pendingAction);

            // Serialize step result: [obs_len(int32)] [obs floats] [reward(float32)] [done(byte)]
            using (MemoryStream ms = new MemoryStream())
            using (BinaryWriter bw = new BinaryWriter(ms))
            {
                bw.Write(obs.Length);
                Debug.LogWarning($"obs.Length: {obs.Length}");  // 271
                foreach (float f in obs) { bw.Write(f); }
                bw.Write(reward);
                bw.Write(done ? (byte)1 : (byte)0);
                pendingResponse = ms.ToArray(); 
                Debug.LogWarning($"pendingResponse size: {pendingResponse.Length}");    //1093
            }

            responseReady.Set(); // wake network thread
        }
    }

    // =============================================================================================
    // HANDSHAKE STRUCTURE
    // =============================================================================================

    /// <summary>
    /// Sends the current observation and action vector lengths to the client.
    /// Called on connection and after each reset to support dynamic model variations.
    /// </summary>
    private void SendHandshake(BinaryWriter bw)
    {
        try
        {
            int obsLen = 271;    // TODO: automate!
            int actLen = 40;

            // Handshake packet format:
            // [int32: opcode=100]  [int32: obsLen]  [int32: actLen]
            bw.Write(100);
            bw.Write(obsLen);
            bw.Write(actLen);
            bw.Flush();

            Debug.Log($"[SocketServer] Handshake sent (obs={obsLen}, act={actLen})");
        }
        catch (Exception ex)
        {
            Debug.LogError($"[SocketServer] Handshake failed: {ex}");
        }
    }
}