from PythonToUnity_EnvironmentClient import UnityEnvClient
import numpy as np

# This script was generated by OpenAI's GPT-5 model.

print("🔌 Connecting to Unity environment…")
env = UnityEnvClient()

print("✅ Connected. Requesting environment reset.")
env.reset()

# One test action vector ('1' to actuators, '0' to thrusters)
test_action = [1.0] * 16 + [0.0] * 24 #np.zeros(6, dtype=np.float32)

print("➡️  Sending test action:", test_action)
obs, reward, done = env.step(test_action)

# ---- Explicit diagnostics ----
if isinstance(obs, (list, np.ndarray)):
    print(f"🔹 Observation length: {len(obs)}")
    print(f"🔹 First 5 observation values: {obs[:5]}")
else:
    print("⚠️  Observation not received or wrong type:", obs)

print(f"🔹 Reward value: {reward}")
print(f"🔹 Done flag:   {done}")

env.close()
print("🔒 Connection closed.")